src/Entity/User.php
<?php
// src/Entity/User.php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\OneToMany(targetEntity="App\Entity\Bankcard", mappedBy="userId")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        $this->bankcards = new ArrayCollection();
        // your own logic
    }

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }

    /**
     * Date/Time of last activity
     *
     * @var \DateTime
     *
     * @ORM\Column(name="last_activity_at", type="datetimetz", nullable=true)
     */
    protected $lastActivityAt;

    /**
     * @var string
     * @ORM\Column(name="telnr", type="string", length=255, nullable=true)
     */
    private $telnr;
    /**
     * @var string
     * @ORM\Column(name="mobilenr", type="string", length=255, nullable=true)
     */
    private $mobilenr;
    /**
     * @var string
     * @ORM\Column(name="first_name", type="string", length=255, nullable=true)
     */
    private $first_name;
    /**
     * @var string
     * @ORM\Column(name="insertion", type="string", length=255, nullable=true)
     */
    private $insertion;
    /**
     * @var string
     * @ORM\Column(name="last_name", type="string", length=255, nullable=true)
     */
    private $last_name;
    /**
     * @var string
     * @ORM\Column(name="adres", type="string", length=255, nullable=true)
     */
    private $adres;
    /**
     * @var string
     * @ORM\Column(name="zip", type="string", length=255, nullable=true)
     */
    private $zip;
    /**
     * @var string
     * @ORM\Column(name="city", type="string", length=255, nullable=true)
     */
    private $city;
    /**
     * @var string
     * @ORM\Column(name="country", type="string", length=255, nullable=true)
     */
    private $country;

//    /**
//     * @ORM\OneToMany(targetEntity="App\Entity\Bankcard", mappedBy="userId")
//     */
//    private $bankcards;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastActivityAt(): ?\DateTimeInterface
    {
        return $this->lastActivityAt;
    }

    public function setLastActivityAt(?\DateTimeInterface $lastActivityAt): self
    {
        $this->lastActivityAt = $lastActivityAt;

        return $this;
    }

    public function getTelnr(): ?string
    {
        return $this->telnr;
    }

    public function setTelnr(?string $telnr): self
    {
        $this->telnr = $telnr;

        return $this;
    }

    public function getMobilenr(): ?string
    {
        return $this->mobilenr;
    }

    public function setMobilenr(?string $mobilenr): self
    {
        $this->mobilenr = $mobilenr;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getInsertion(): ?string
    {
        return $this->insertion;
    }

    public function setInsertion(?string $insertion): self
    {
        $this->insertion = $insertion;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAdres(): ?string
    {
        return $this->adres;
    }

    public function setAdres(?string $adres): self
    {
        $this->adres = $adres;

        return $this;
    }

    public function getZip(): ?string
    {
        return $this->zip;
    }

    public function setZip(?string $zip): self
    {
        $this->zip = $zip;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }


//    /**
//     * @return Collection|Bankcard[]
//     */
//    public function getBankcards(): Collection
//    {
//        return $this->bankcards;
//    }
//
//    public function addBankcard(Bankcard $bankcard): self
//    {
//        if (!$this->bankcards->contains($bankcard)) {
//            $this->bankcards[] = $bankcard;
//            $bankcard->setUserId($this);
//        }
//
//        return $this;
//    }
//
//    public function removeBankcard(Bankcard $bankcard): self
//    {
//        if ($this->bankcards->contains($bankcard)) {
//            $this->bankcards->removeElement($bankcard);
//            // set the owning side to null (unless already changed)
//            if ($bankcard->getUserId() === $this) {
//                $bankcard->setUserId(null);
//            }
//        }
//
//        return $this;
//    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

class UserType extends AbstractType
{
    protected $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if ($this->security->isGranted('ROLE_ADMIN')) {
            $builder
                ->add('username')
                ->add('usernameCanonical')
                ->add('email')
                ->add('emailCanonical')
                ->add('enabled')
                ->add('salt')
                ->add('password')
                ->add('lastLogin')
                ->add('confirmationToken')
                ->add('passwordRequestedAt')
                ->add('roles')
                ->add('lastActivityAt');
            }
        $builder
            ->add('telnr')
            ->add('mobilenr')
            ->add('first_name')
            ->add('insertion')
            ->add('last_name')
            ->add('adres')
            ->add('zip')
            ->add('city')
            ->add('country');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    protected $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/", name="user_index", methods="GET")
     */
    public function index(): Response
    {
        if ($this->security->isGranted('ROLE_ADMIN')) {
            $users = $this->getDoctrine()->getRepository(User::class)->findAll();
        } elseif ($this->security->isGranted('ROLE_USER')) {
//            $users = $this->getDoctrine()->getRepository(User::class)->findBy(['id' => $this->security->getUser()]);
            return $this->render('user/show.html.twig', ['user' => $this->getUser()]);

        } else {
            return $this->render('message/security.html.twig');
        }
        return $this->render('user/index.html.twig', ['users' => $users]);
    }

    /**
     * @Route("/new", name="user_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        if ($this->security->isGranted('ROLE_ADMIN')) {
            $user = new User();
            $form = $this->createForm(UserType::class, $user);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($user);
                $em->flush();

                return $this->redirectToRoute('user_index');
            }

            return $this->render('user/new.html.twig', [
                'user' => $user,
                'form' => $form->createView(),
            ]);
        } else {
            return $this->render('message/security.html.twig');
        }
    }

    /**
     * @Route("/{id}", name="user_show", methods="GET")
     */
    public function show(User $user): Response
    {
        if ($this->security->isGranted('ROLE_ADMIN')) {
            return $this->render('user/show.html.twig', ['user' => $user]);
        } elseif ($this->security->isGranted('ROLE_USER') && $user == $this->getUser()) {
            return $this->render('user/show.html.twig', ['user' => $this->getUser()]);
        } else {
            return $this->render('message/security.html.twig');
        }
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods="GET|POST")
     */
    public function edit(Request $request, User $user): Response
    {

        if ($this->security->isGranted('ROLE_ADMIN') || $this->security->isGranted('ROLE_USER') && $user == $this->getUser()) {
            $form = $this->createForm(UserType::class, $user);
        } else {
            return $this->render('bundles/TwigBundle/Exception/error404.html.twig');
        }
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('user_edit', ['id' => $user->getId()]);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods="DELETE")
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($user);
            $em->flush();
        }

        return $this->redirectToRoute('user_index');
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1 class="text-center">Edit User</h1>
    <div class="container">

        {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

        <a href="{{ path('user_index') }}">back to list</a>

        {{ include('user/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

{% endblock %}
{% block body %}
    <body style="background-color: lightblue;">

    <h1 class="text-center">User index</h1>

    <table id="myTable" class="table table-striped display">
        <thead>
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Enabled</th>
            <th>LastLogin</th>
            <th>Roles</th>
            <th>Id</th>
            <th>LastActivityAt</th>
            <th>First_name</th>
            <th>Insertion</th>
            <th>Last_name</th>
            <th>Country</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.username | capitalize }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.enabled ? 'Yes' : 'No' }}</td>
                <td>{{ user.lastLogin ? user.lastLogin|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.roles ? user.roles|join(', ') : '' }}</td>
                <td>{{ user.id }}</td>
                <td>{{ user.lastActivityAt }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.insertion }}</td>
                <td>{{ user.lastName }}</td>

                <td>{{ user.country }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="23">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('user_new') }}">Create new</a>
    {% endif %}
    </body>

{% endblock %}
{% block scripts %}
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1 class="text-center">Create new User</h1>
    <div class="container">

        {{ include('user/_form.html.twig') }}

        <a href="{{ path('user_index') }}">back to list</a>
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table table-striped">
        <tbody>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>UsernameCanonical</th>
                <td>{{ user.usernameCanonical }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>EmailCanonical</th>
                <td>{{ user.emailCanonical }}</td>
            </tr>
            <tr>
                <th>Enabled</th>
                <td>{{ user.enabled ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Salt</th>
                <td>{{ user.salt }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>LastLogin</th>
                <td>{{ user.lastLogin ? user.lastLogin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>ConfirmationToken</th>
                <td>{{ user.confirmationToken }}</td>
            </tr>
            <tr>
                <th>PasswordRequestedAt</th>
                <td>{{ user.passwordRequestedAt ? user.passwordRequestedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>LastActivityAt</th>
                <td>{{ user.lastActivityAt }}</td>
            </tr>
            <tr>
                <th>Telnr</th>
                <td>{{ user.telnr }}</td>
            </tr>
            <tr>
                <th>Mobilenr</th>
                <td>{{ user.mobilenr }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ user.firstName }}</td>
            </tr>
            <tr>
                <th>Insertion</th>
                <td>{{ user.insertion }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ user.lastName }}</td>
            </tr>
            <tr>
                <th>Adres</th>
                <td>{{ user.adres }}</td>
            </tr>
            <tr>
                <th>Zip</th>
                <td>{{ user.zip }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ user.city }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ user.country }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}